name: Publish Docker image to Dockerhub and GHCR

on:
  push:
    branches: [ main ]
jobs:
  docker:
    run-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
      - uses: docker/login-action@v1
      - with: 
        username: ${{ secrects.DOCKERHUB_USERNAME }}
        password: ${{ secrects.DOCKERHUB_ACCESS_TOKEN }}

      
