name: Publish Docker image to Dockerhub and GHCR

on:
  push:
    branches:
      - 'main'
      # add additional branches that should build to images here
      # they will be tagged based on the branch name IE kener:test
      #- 'test'
    tags:
      - '*.*.*'
    # don't trigger if just updating docs
    paths-ignore:
      - 'docs.md'
      - 'README.md'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    # only run if we've specified image tag to push to
    if: ${{ vars.DOCKERHUB_IMAGE_NAME != '' ||  vars.GHCR_IMAGE_NAME != '' }}
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        if: ${{ github.event_name != 'pull_request' && vars.DOCKERHUB_IMAGE_NAME != '' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
